### PR TITLE
Feat: Add SSL/HTTPS configuration option

### LINKED ISSUE #27: Feat: Option to configure SSL cert for curl
**TL;DR** connecting `obsidian-bridge` to the REST API via. HTTPS/SSL should be much easier for users to set up. I propose either a setup option or environment variable which tells `curl` what to pass with the `--cacert` flag. This would not be a breaking change. I will fork this repository, implement the solution, and submit a PR myself; I am creating this issue to also start a discussion and let folks weigh in on how they think this implementation should be done.

# Motivation

If you want to use the SSL encrypted port on the Local REST API plugin, you need to "trust" the certificate generated by the plugin. This is fairly easy to set up in a web browser (which is also the main use case of the REST API plugin). 

However, for use with obsidian-bridge, I really struggled. Since bridge uses `curl` under the hood, it's as trivial as passing a CLI flag pointing to the certificate file to all `curl` calls. `obsidian-bridge` does not expose this as a setup option, however. So, if a user wants to use SSL, they need to either modify this plugin's source code themselves, which is time consuming and not very noob friend, *or* figure out how to "trust" the certificate system-wide, which differs greatly among operating systems, and is also quite technically involved. 

Either option is a lot of work and research for the user to set up, and it's much easier to just fall back on the default option of an unencrypted connection, which is bad security practice, even despite the fact that it's only a localhost connection.

# Proposed Solution

A configuration option that can be passed to the `setup` function when the plugin is loaded. This option could contain a string which is the path to the certificate file that users can copy from the Local REST API interface. Alternatively, an environment variable could also contain this path. `obsidian-bridge` would pass this string as the value of the `--cacert` flag of `curl`. 

**Proposed default:** If the configuration option is `nil`, or the environment variable is not set (depending on which implementation is chosen), then the plugin should omit the `--cacert` flag in all `curl` calls, retaining its previous behavior. Therefore, this would not be a breaking change, and users would not need to update their configuration upon updating this plugin if they want to keep using unencrypted HTTP traffic. 

# Implementation

I will fork this repository, implement the change, and submit a PR myself. I'm creating this issue for reference, as well as to get feedback on this idea. So @oflisback don't worry too much about this, because this is less of a "feature request" and more of an "I'm going to implement this feature and submit a PR, is my proposed approach fine, should I change it somehow, or should I just not bother because you don't want this feature in the plugin?"

I look forward to hearing what you all think about this.

### PR DESCRIPTION
**Pull request by ficcdaf**
This is my implementation and fixes #27 . I also updated the README file with instructions on how to use the new option. Please note that I also modernized the `lazy.nvim` setup instructions in the readme; the lazy docs say to discourage users from the 

```lua
config = function() require("plugin.name").setup({opts}) end,
```

pattern, instead encouraging that options be passed directly to the `opts = {}` field of the spec.  

The functions I implemented are extensible in case we ever need to pass more arguments to `curl` in the future. I also chose to build the `curl` "raw" arguments in the config file on the plugin being loaded, instead of dynamically generating it on every API call. It makes `config.lua` a little more verbose, but it should result in a performance boost since the table doesn't need to be generated on every API call. 

Please note that I also changed the error reporting in `config.lua` to use `vim.notify` because it is a cleaner experience for the user; the errors all have a custom message anyways, and the stack trace distracts the user from that message. 

I tested this pretty extensively with different combinations of settings (or lack thereof). I also added a warning if the user provides a cert with an unencrypted HTTP URL, an error if the user does _not_ provide a cert with an HTTPS URL, and an error message if the provided cert is an invalid path (the `curl` errors are on the "debug" level meaning it may be suppressed for some users, so they might not know what the problem is).

This was fun to implement. Please let me know if I should change anything.

### CODE REVIEW

**Comment by oflisback** [comment]
Thanks a lot! I will give this a spin tomorrow at the latest :pray:

**Review by oflisback — COMMENTED** [review]
That's a beautiful PR, well done and much appreciated!

Thanks for aligning the Lazy config with best practice, this looks a lot cleaner.

Regarding `vim.notify`, perhaps we should use that consistently instead of `vim.api.nvim_err_writeln` then, what do you think?

- When I tried using the cert based on the instruction I get this curl error message:

```
post https://localhost:27124/open/foo/bar.md - curl error exit_code=60 stderr={ "curl: (60) SSL certificate problem: self-signed certificate", "More details here: https://curl.se/docs/sslcerts.html", "", "curl failed to verify the legitimacy of the server and therefore could not", "establish a secure connection to it. To learn more about this situation and", "how to fix it, please visit the webpage mentioned above." }
```
Which makes sense, have you made any specific config for it, something we can recommend? I'm using curl `8.10.1`.

Perhaps we should call the certificate `.crt` in the example config and perhaps point the users to the way to download the cert:

image

which will download the `.crt` file directly.

Again thanks a lot, let me know your thoughts.

**Comment by ficcdaf** [comment]
For some reason on my system (Linux + i3wm) clicking the download cert link did not download anything, so personally I had to copy it from the text field in the Advanced Settings and write it to a file -- we could add both options to the readme instructions. I don't think it actually matters what the extension of the file is -- `.crt` or `.pem` -- since really it's just a plaintext file. But I agree, updating the example config to use `.crt` could reduce confusion for the users.

I think I've narrowed down the issue. The SSL certificate is only bound to the address `127.0.0.1`, and not `localhost`. For example:

```bash
# This works 
curl --cacert ~/.ssl/obsidian-bridge.pem -H "Authorization: Bearer $OBSIDIAN_REST_API_KEY" https://127.0.0.1:27124/vault/

# This returns an error
curl --cacert ~/.ssl/obsidian-bridge.pem -H "Authorization: Bearer $OBSIDIAN_REST_API_KEY" https://localhost:27124/vault/
``` 

Could you please try changing your `obsidian_server_address` to use `127.0.0.1` and try again with the cert? If that works for you, then I can add some code to this PR that will check whether the user has provided a `localhost` address with a cert, and display a warning telling them to use `127.0.0.1` instead. I'll also update the readme in that case.

Re `vim.notify`, I agree it would be better to use it consistently throughout the rest of the plugin. Perhaps `WARNING` for failed `curl` requests, `ERROR` for things like missing API key, and `INFO` for other types of information. We could open a separate issue for this and have a separate PR for it.

**Comment by oflisback** [comment]
I tried `127.0.0.1`, but same result. The curl error mentions that the issue is the self-signed certificate. [plenary curl](https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/curl.lua#L17) has an `insecure` option that I thought would help but in my quick test it didn't. I can look into it closer tomorrow, but it's surprising that I get that error and not you.

Apart from that I agree with everything you write so when we have that sorted out and details (`.crt`, `https://127.0.0.1:27124` as example url) we can merge :rocket:

**Comment by ficcdaf** [comment]
Hmmm, that's really strange... the "self signed certificate" error is the same as what you get if you try to connect via HTTPS without any cert at all. So it seems as though `curl` is not properly being forced to trust the certificate you gave it. 

have you tried testing it with curl in the CLI, outside of Neovim? If you can't get it to work with a simple `curl` call from the terminal (like the command I gave above), then I wonder if there is a problem with your certificate file itself? Since I'm not able to get the file from the "link" in the settings page, could you please check that file and compare it with what's inside the text box in the "advanced settings" and let me know if they are the same? And if they are different, you could try to copy the certificate from the text box like I did and try using that instead. That could help us narrow down what's going on. 

My last idea is that it may be to do with the operating system? For example, if you are on Mac, I wouldn't be surprised if there was some extra step you needed to take in order for to force curl to "trust" the certificate.

So for now if you could 

1. Test the certificate with a `curl` call from the terminal
2. Check if the "two" certificates in the REST API settings are really the same 

Then I think we can narrow down where the problem is. Also, if you don't mind sharing your operating system, I can also do some research into potential causes. 

Thanks!

**Comment by ficcdaf** [comment]
I did a bit of searching and it's also possible that the `.crt` file provided by the API plugin is in a binary format, which is not compatible with curl. Also when you are testing curl in the terminal please supply the `-v` flag for verbose output, maybe we can learn more from it.

**Comment by oflisback** [comment]
Now it works for me too! My config didn't point to the correct cert and it was unfortunate that curl then complains
about the cert being self-signed. Anyway now it works, thanks for your patience!

* You are right that it needs to be `127.0.0.1` and not `localhost`.
* The `.crt` file downloadable via their link in settings is not binary, it's exactly equivalent to the one you copy from the advanced
settings but it doesn't matter, the instructions regarding that are fine as is I think.

If you have a chance, please update the two details about .crt ending and https://127.0.0.1:27124 as example url, then we'll merge.

Thanks!

**Comment by ficcdaf** [comment]
Great. I'll actually add in a quick check to warn the user if they provide a `localhost` address; and I will update the readme.

**Comment by ficcdaf** [comment]
@oflisback Please see above. I updated the documentation, as well as added a new config option, `warnings`, so the user can disable the misconfiguration warnings if they prefer.

**Pull request merged**
